"""
backend/mcp/github_mcp.py

ScholarForge — Phase 8B: GitHub MCP

Creates a new public GitHub repo, pushes generated code files to it along
with an auto-written README, and returns the repo URL. Uses GITHUB_TOKEN
from environment (needs the "repo" scope).
"""

import os

from dotenv import load_dotenv
from github import Github, Auth, GithubException

load_dotenv()


def push_generated_code(repo_name: str, files: dict, description: str, token: str = None) -> str:
    """
    Create a new public GitHub repo, push all generated code files plus a
    README, and return the repo URL.

    `files` should be a dict of {filename: code_string}.
    `token` should be the GitHub Personal Access Token of the user the repo
    is being created for. Falls back to the GITHUB_TOKEN env var only when
    no token is explicitly passed in (e.g. for standalone CLI testing of
    this file) — in the real pipeline, the caller should always pass the
    requesting user's own token rather than relying on this fallback, so
    code isn't pushed into the server operator's account on their behalf.

    Returns the repo URL on success, or a string starting with "ERROR:" on failure.
    """
    token = token or os.getenv("GITHUB_TOKEN")
    if not token:
        return "ERROR: No GitHub token provided."

    try:
        auth = Auth.Token(token)
        g = Github(auth=auth)
        user = g.get_user()

        try:
            repo = user.create_repo(
                name=repo_name,
                description=description[:350],  # GitHub caps repo description length
                private=False,
                auto_init=True,  # creates an initial commit so file operations work cleanly
            )
        except GithubException as e:
            if e.status == 422:
                return f"ERROR: A repo named '{repo_name}' already exists on your account."
            return f"ERROR: GitHub repo creation failed: {e}"

        readme_content = f"# {repo_name}\n\n{description}\n\n## Generated Files\n\n"
        readme_content += "\n".join(f"- `{filename}`" for filename in files)
        readme_content += "\n\n---\n*Generated by ScholarForge.*\n"

        # auto_init=True already created a default README.md — update it rather than re-creating.
        existing_readme = repo.get_contents("README.md")
        repo.update_file(
            existing_readme.path,
            "Add ScholarForge-generated README",
            readme_content,
            existing_readme.sha,
        )

        for filename, code in files.items():
            repo.create_file(filename, f"Add generated {filename}", code)

        return repo.html_url

    except Exception as e:
        return f"ERROR: GitHub push failed: {e}"


if __name__ == "__main__":
    sample_files = {
        "model_architecture.py": "# Sample generated code\nclass Model:\n    pass\n",
    }
    url = push_generated_code(
        repo_name="scholarforge-test-repo",
        files=sample_files,
        description="Test repo created by ScholarForge's GitHub MCP integration.",
    )
    print(url)
